### ISSUE TITLE
rfdocserver cannot find .resource files

### ISSUE THREAD

**Issue by johndoorzon** [juha-ylikoski/rfdocserver#8]
I tried rfdocserver and only could get it to work after renaming my resource files from .resource to .robot.
Please include .resource files (I think this is the recommended way to use now, .robot for test files and .resource for resource files).

**Comment by juha-ylikoski** [comment]
I added .resource to supported file formats and released new version on github and on pypi https://pypi.org/project/rfdocserver/1.0.2/#description
